#!/usr/bin/env python

import subprocess;
import xml.etree.ElementTree as ET;

def getcputemperature():
	try:
		fp = open('/sys/class/thermal/thermal_zone0/temp', 'r');
		text = fp.readline();
		fp.close();
		return int((float)(text) / 1000.0);
	except:
		return None;

def getgputemperature():
	try:
		# Fetch XML data from nvidia-smi
		nvidia_smi = subprocess.Popen(['nvidia-smi', '-q', '-x'], stdout=subprocess.PIPE);
		stdout, stderr = nvidia_smi.communicate();
		if (nvidia_smi.returncode != 0):
			return None;

		# Parse XML data
		tree = ET.fromstring(stdout);
		temperature = list(tree.findall('./gpu/temperature/gpu_temp'))[0].text;
		return int(temperature.replace(' C', ''));

	except Exception, e:
		return None;

if __name__ == '__main__':
	import sys, time, getopt;
	usage = 'Usage: %s [-i interval] [-o output_file]' % sys.argv[0];
	interval = 5;
	output_file = 'temperature_log.csv';

	try:
		opts, args = getopt.getopt(sys.argv[1:], 'i:o:h');
		for o, a in opts:
			if o == '-i':
				interval = int(a);
			elif o == '-o':
				output_file = a;
			elif o == '-h':
				print(usage);
				exit(0);
	except getopt.GetoptError as err:
		print(usage);
	except Exception, e:
		print(usage);

	try:
		while True:
			fp = open(output_file, 'a');
			fp.write("%s\t%d\t%d\n" % (time.strftime('%Y-%m-%dT%H:%M:%S', time.localtime()), getcputemperature(), getgputemperature()));
			fp.close();
			time.sleep(interval);
	except KeyboardInterrupt:
		pass;
	except Exception, e:
		print(str(e));
		exit(1);
	exit(0);

